name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish:
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && startsWith(github.ref, 'refs/tags/v'))
    uses: iyulab/shared/.github/workflows/publish-npm.yml@1802449344d6384c28bfe8706e28a822e8a3fd9c
    with:
      node_version: "22"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
